do
msgbox "THIS IS A FAKE HACK, IT IS NOT REAL IF YOU WANT TO DISABLE IT, RIGHT CLICK ON TASKBAR GO TO TASK MANAGER AND IF YOU SEE A BLU, GREEN, AND RED BOX CLICK IT THEN CLICK END TASK. NO YOU HAVE NOT GOTTEN ANY MALWARE SO DO NOT WORRY AND IF THAT DOES NOT WORK, DRAG FAKEHACK.VBS TO YOUR TRASH BIN AND RESTART YOUR COMPUTOR (i think)"
loop